config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :accounts
  resources :balances
  get '/current-month', to: 'pages#current_month', as: 'current_month'
  get '/current-year', to: 'pages#current_year', as: 'current_year'
  get '/current-month-graph', to: 'pages#current_month_graph', as: 'current_month_graph'
  get '/current-year-graph', to: 'pages#current_year_graph', as: 'current_year_graph'
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :balances

  scope :short_term, -> { where(category: 'short-term').order('position ASC') }
  scope :long_term, -> { where(category: 'long-term').order('position ASC') }
  scope :property, -> { where(category: 'property').order('position ASC') }

  def current_balance
    if name == 'Starling'
      request = RestClient.get "https://api.starlingbank.com/api/v1/accounts/balance", { authorization: "Bearer #{ENV['STEVE_TOKEN']}" }
      balance = ActiveSupport::JSON.decode(request)
      balance['effectiveBalance']
    else
      balances&.in_date_order.last&.amount || 0
    end
  end

  def balance_on(date)
    balances&.in_date_order.created_before(date).last&.amount || 0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ActiveRecord::Base
  belongs_to :account, dependent: :destroy

  scope :in_date_order, -> { order('created_at ASC') }

  scope :created_before, ->(date) do
    where('balances.created_at <= ?', date)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
    get_chart_data
  end

  private

  def get_chart_data
    @dates = []
    @balances = []

    @account.balances.in_date_order.each do |balance|
      @dates << balance.created_at.to_date.to_formatted_s(:long_ordinal)
      @balances << balance.amount
    end

    gon.dates = @dates
    gon.balances = @balances
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def index
    @balances = Balance.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :get_base_data

  def home
    @net_worth = 0
    @accounts.each do |account|
      @net_worth += account.current_balance
    end
  end

  def current_month_graph
    get_daily_balances
  end

  def current_year_graph
    get_monthly_balances
  end

  def current_month
    Date.new(@year, @month, -1).day.times do |index|
      day = (index + 1)
      net_worth_today = 0
      @accounts.each do |account|
        net_worth_today += account.balance_on(Date.new(@year, @month, day) + 1.day)
      end
      @daily_balances << net_worth_today
    end
  end

  def current_year
    12.times do |index|
      month = (index + 1)
      net_worth_today = 0
      @accounts.each do |account|
        net_worth_today += account.balance_on(Date.new(@year, month, -1))
      end
      @monthly_balances << net_worth_today
    end
  end

  private

  def get_base_data
    @accounts = Account.all.includes(:balances)
    @current_month = Time.now.strftime("%B")
    @current_year = Time.now.strftime("%Y")
    @month = Time.now.month
    @year = Time.now.year
    @daily_balances = []
    @monthly_balances = []
  end

  def get_daily_balances
    get_days

    Time.now.day.times do |index|
      day = (index + 1)
      net_worth_today = 0
      @accounts.each do |account|
        net_worth_today += account.balance_on(Date.new(@year, @month, day) + 1.day)
      end
      @daily_balances << net_worth_today
    end

    gon.daily_balances = @daily_balances
  end

  def get_monthly_balances
    get_months

    Time.now.month.times do |index|
      month = (index + 1)
      net_worth_today = 0
      @accounts.each do |account|
        net_worth_today += account.balance_on(Date.new(@year, month, -1))
      end
      @monthly_balances << net_worth_today
    end
    gon.monthly_balances = @monthly_balances
  end

  def get_days
    gon.days = []
    Time.now.day.times do |index|
      gon.days << index + 1
    end
  end

  def get_months
    gon.months = []
    Time.now.month.times do |index|
      gon.months << Date::MONTHNAMES[index + 1]
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def total_current_balance(accounts)
    total = 0
    accounts.each do |account|
      total += account.current_balance
    end

    total
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def red_or_green(number)
    (number < 0) ? 'red' : 'green'
  end
end

app/views/accounts/_transactions.html.erb
<div class="balance">
  <h2 class="balance__top"><%= category %></h2>

  <div class="balance__accounts">
    <% accounts.each do |account| %>
      <% unless account.current_balance == 0.0 %>
        <div class="balance__account">
          <div class="balance__account-name">
            <%= link_to account.name, account %>
          </div>
          <div class="balance__account-amount <%= red_or_green(account.current_balance) %>">
            <%= number_to_currency account.current_balance, unit: '£', strip_insignificant_zeros: true %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <h3 class="balance__bottom">
    <div class="balance__account">
      <div class="balance__account-name">
        <%= category %> total:
      </div>
      <% total = total_current_balance(accounts) %>
      <div class="balance__account-amount <%= red_or_green(total) %>">
        <%= number_to_currency total, unit: '£', strip_insignificant_zeros: true %>
      </div>
    </div>
  </h3>
</div>

app/views/accounts/index.html.erb
<h1 class='center'>Current Balances</h1>

<div class="balances">
  <%= render partial: 'transactions', locals: { category: 'Short term', accounts: @accounts.short_term } %>
  <%= render partial: 'transactions', locals: { category: 'Long term', accounts: @accounts.long_term } %>
  <%= render partial: 'transactions', locals: { category: 'Property', accounts: @accounts.property } %>
</div>

<br>
<h2 class="center">
  <div class="balances">
    <div class="balance no-border">
      <div class="balance__account">
        <div class="balance__account-name">
          Net worth:
        </div>
        <% total = total_current_balance(@accounts) %>
        <div class="balance__account-amount <%= red_or_green(total) %>">
          <%= number_to_currency total, unit: '£', strip_insignificant_zeros: true %>
        </div>
      </div>
    </div>
  </div>
</h2>

app/views/accounts/show.html.erb
<h1 class="center"><%= @account.name %></h1>

<canvas id="accountHistory"></canvas>

<br>

<h1 class="center">Balance History</h1>

<div class="balances balances--center">
  <div class="balance">
    <div class="balance__accounts">
      <% @account.balances.in_date_order.each do |balance| %>
        <div class="balance__account">
          <div class="balance__account-name">
            <%= balance.created_at.to_date.to_formatted_s(:long_ordinal) %>
          </div>
          <div class="balance__account-amount <%= red_or_green(balance.amount) %>">
            <%= number_to_currency balance.amount, unit: '£', strip_insignificant_zeros: true %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  var accountHistoryChart = $("#accountHistory");

  var accountHistory = new Chart(accountHistoryChart, {
      type: 'line',
      data: {
          labels: gon.dates,

          datasets: [{
              label: '£',
              data: gon.balances,
              backgroundColor: ['#0D791C'],
              borderColor: ['#0D791C'],
              borderWidth: 1,
              fill: false,
          }]
      },
      options: {
        responsive: false,
        title:{
            display: false,
            text:'History'
        },
        tooltips: {
            mode: 'index',
            intersect: false,
        },
        hover: {
            mode: 'nearest',
            intersect: true
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Month'
                }
            }],
            yAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Value'
                }
            }]
        }
      }
  });
</script>

app/views/balances/index.html.erb
<h1>Balances</h1>

<% @starling_balances.each do |balance| %>
<%= balance.created_at.to_date.to_formatted_s(:long_ordinal) %>
<%= balance.amount %>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar">
  <%= link_to "My Finances", root_path, class: 'navbar__item' %>

  <%= link_to accounts_path, class: "navbar__item" do %>
    <i class="fa fa-money"></i>
    Accounts
  <% end %>

  <%= link_to current_month_path, class: "navbar__item" do %>
    <i class="fa fa-calendar"></i>
    <%= "#{Time.now.strftime("%B")}" %>
  <% end %>

  <%= link_to current_year_path, class: "navbar__item" do %>
    <i class="fa fa-calendar"></i>
    <%= "#{Time.now.strftime("%Y")}" %>
  <% end %>

  <%= link_to current_month_graph_path, class: "navbar__item" do %>
    <i class="fa fa-line-chart"></i>
    <%= "#{Time.now.strftime("%B")}" %>
  <% end %>

  <%= link_to current_year_graph_path, class: "navbar__item" do %>
    <i class="fa fa-line-chart"></i>
    <%= "#{Time.now.strftime("%Y")}" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <title>Finances</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhaina" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"></link>

  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/current_month.html.erb
<h1 class='center'><%= @current_month %></h1>

<div class="calendar">
  <% @daily_balances.each_with_index do |balance, index| %>
    <div class="calendar__square <%= 'grey' if (index + 1) == Time.now.day %>">
      <div class="calendar__square-title">
        <h2><%= index + 1 %></h2>
      </div>

      <div class="calendar__balance">
        <%= ((index + 1) <= Time.now.day) ? (number_to_currency balance, unit: '£', strip_insignificant_zeros: true) : "<i class='fa fa-clock-o'></i>".html_safe %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/current_month_graph.html.erb
<h1 class='center'><%= @current_month %></h1>

<canvas id="netWorthByMonth"></canvas>

<script>
  var netWorthByMonthChart = $("#netWorthByMonth");

  var netWorthByMonth = new Chart(netWorthByMonthChart, {
      type: 'line',
      data: {
          labels: gon.days,

          datasets: [{
              label: '£',
              data: gon.daily_balances,
              backgroundColor: ['#0D791C'],
              borderColor: ['#0D791C'],
              borderWidth: 1,
              fill: false,
          }]
      },
      options: {
        responsive: false,
        title:{
            display: false,
            text:'Net Worth'
        },
        tooltips: {
            mode: 'index',
            intersect: false,
        },
        hover: {
            mode: 'nearest',
            intersect: true
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Month'
                }
            }],
            yAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Value'
                }
            }]
        }
      }
  });
</script>

app/views/pages/current_year.html.erb
<h1 class='center'><%= @current_year %></h1>

<div class="calendar">
  <% @monthly_balances.each_with_index do |balance, index| %>
    <div class="calendar__square calendar__square--large <%= 'grey' if (index + 1) == Time.now.month %>">
      <div class="calendar__square-title">
        <h2><%= Date::MONTHNAMES[index + 1] %></h2>
      </div>

      <div class="calendar__balance">
        <%= ((index + 1) <= Time.now.month) ? (number_to_currency balance, unit: '£', strip_insignificant_zeros: true) : "<i class='fa fa-clock-o'></i>".html_safe %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/current_year_graph.html.erb
<h1 class='center'><%= @current_year %></h1>

<canvas id="netWorthByYear"></canvas>

<script>
  var netWorthByYearChart = $("#netWorthByYear");

  var netWorthByYear = new Chart(netWorthByYearChart, {
      type: 'line',
      data: {
          labels: gon.months,

          datasets: [{
              label: '£',
              data: gon.monthly_balances,
              backgroundColor: ['#0D791C'],
              borderColor: ['#0D791C'],
              borderWidth: 1,
              fill: false,
          }]
      },
      options: {
        responsive: false,
        title:{
            display: false,
            text:'Net Worth'
        },
        tooltips: {
            mode: 'index',
            intersect: false,
        },
        hover: {
            mode: 'nearest',
            intersect: true
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Month'
                }
            }],
            yAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Value'
                }
            }]
        }
      }
  });
</script>

app/views/pages/home.html.erb
<h1 class="jumbo <%= red_or_green(@net_worth) %>"><%= number_to_currency @net_worth, unit: '£', strip_insignificant_zeros: true %></h1>